In [1]:
import YummyHub

In [2]:
YummyHub.main()

WELCOME TO THE DIGITAL RECIPE BOOK
This application helps you easily store, retrieve, and
manage your favorite cooking recipes all in one place.

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Generate a shopping list
8. Exit

Enter your choice (1-8):  5
Enter recipe name:  baked salmon
Enter a rating from 1 to 5:  3.8

First rating recorded: 3.8/5.

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Generate a shopping list
8. Exit

Enter your choice (1-8):  6

            name  rating
       machboose     4.8
           pasta     4.0
  fruit smoothie     4.0
   avocado toast     3.9
    baked salmon     3.8
        Pancakes     3.5
    egg sandwich     2.5
    cesser salad     2.2
chia seed boding     2.0
 turkey sandwich     2.0
             tea     2.0

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Generate a shopping list
8. Exit

Enter your choice (1-8):  8

Thank you for using DIGITAL RECIPE BOOK. Goodbye!

In [1]:
import YummyHubFinal

In [2]:
YummyHubFinal.main()

WELCOME TO THE DIGITAL RECIPE BOOK
This application helps you easily store, retrieve, and
manage your favorite cooking recipes all in one place.

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Exit

Enter your choice (1-7):  1

=== Add a New Recipe ===

Enter recipe name:  tea

Please enter ingredients below (separated by commas OR one by one), then type 'done' when finished:

Add ingredient(s):  water
Add ingredient(s):  tea bag
Add ingredient(s):  suger
Add ingredient(s):  done
Enter preparation time in minutes:  4

Please enter cooking instructions step-by-step. Type 'done' when finished:

Step 1:  boil the water
Step 2:  add the tea bag into the cup
Step 3:  add the boil water
Step 4:  done

Difficulty options: Easy, Medium, Hard

Enter recipe difficulty level:  easy

Categorize options: Breakfast, Lunch, Dinner, Dessert

Enter recipe category:  breakfast

Success! Category set to: Breakfast

File recipes.csv has been successfully updated with tea!

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Exit

Enter your choice (1-7):  2
Enter an ingredient to search recipes:  water

=== FOUND RECIPES ===
            name  preparing time difficulty level
           pasta              30           Medium
chia seed boding             120             Easy
             tea               4             Easy

=== ALL RECIPES ===
Name: egg sandwich - Preping Time: 10 mins - Difficulty level: Easy
Name: pasta - Preping Time: 30 mins - Difficulty level: Medium
Name: machboose - Preping Time: 75 mins - Difficulty level: Hard
Name: chia seed boding - Preping Time: 120 mins - Difficulty level: Easy
Name: cesser salad - Preping Time: 20 mins - Difficulty level: Easy
Name: Pancakes - Preping Time: 20 mins - Difficulty level: Medium
Name: fruit smoothie - Preping Time: 10 mins - Difficulty level: Easy
Name: avocado toast - Preping Time: 7 mins - Difficulty level: Easy
Name: baked salmon - Preping Time: 45 mins - Difficulty level: Medium
Name: mrabyan - Preping Time: 60 mins - Difficulty level: Hard
Name: turkey sandwich - Preping Time: 10 mins - Difficulty level: Easy
Name: tea - Preping Time: 4 mins - Difficulty level: Easy

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Exit

Enter your choice (1-7):  3

-----ALL RECIPES----
            name  preparing time
    egg sandwich              10
           pasta              30
       machboose              75
chia seed boding             120
    cesser salad              20
        Pancakes              20
  fruit smoothie              10
   avocado toast               7
    baked salmon              45
         mrabyan              60
 turkey sandwich              10
             tea               4

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Exit

Enter your choice (1-7):  4

=== RANDOM RECIPE ===
    id           name                       ingredients  preparing time                                                                instructions difficulty level category  rating
ec7ca2 fruit smoothie banana; berries; milk; honey; ice              10 add all the ingredients to a blender; blend until smooth; pour into a glass             Easy  Dessert     4.0

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Exit

Enter your choice (1-7):  5
Enter a recipe you'd like to rate:  tea
Enter a rating from 1 to 5:  4.5

First rating has been recorded! The rating is 4.5/5.

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Exit

Enter your choice (1-7):  6

            name  rating
       machboose     5.0
             tea     4.5
           pasta     4.0
  fruit smoothie     4.0
   avocado toast     3.9
        Pancakes     3.5
    egg sandwich     2.5
chia seed boding     0.0
    cesser salad     0.0
    baked salmon     0.0
         mrabyan     0.0
 turkey sandwich     0.0

=== DIGITAL RECIPE BOOK ===
1. Add a new recipe
2. Search for a recipe by ingredient
3. View all recipes
4. Generate a random recipe
5. Rating recipes
6. Sort by rating
7. Exit

Enter your choice (1-7):  7

Thank you for using DIGITAL RECIPE BOOK. Goodbye!

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('recipes.csv')
df

,id,name,ingredients,preparing time,instructions,difficulty level,category,rating
0,6aa5d9,egg sandwich,egg; tost; cheese; salt; black pepper,10,break the egg into the ban; add salt on the eg...,Easy,Breakfast,2.5
1,3c2851,pasta,pasta; water; milk; cheese; tomato paste; oil;...,30,boil the pasta on the water; in another pan mi...,Medium,Dinner,4.0
2,5b0334,machboose,rise; chicken; spices; potato,75,boil chicken with water and spices; boil the r...,Hard,Lunch,5.0
3,5e292e,chia seed boding,chia seeds; milk; mango; yogurt; blueberry; nu...,120,add chia seed to milk and yogurt; cut the frui...,Easy,Dessert,0.0
4,02621a,cesser salad,lettuce; Parmesan cheese; Caesar dressing; Gri...,20,Wash and chop the lettuce; add parmesan; Pour ...,Easy,Dinner,0.0
5,1cca8b,Pancakes,flour; egg; milk; sugar; baking powder; oil; s...,20,mix all ingredients; Heat a lightly greased pa...,Medium,Dessert,3.5
6,ec7ca2,fruit smoothie,banana; berries; milk; honey; ice,10,add all the ingredients to a blender; blend un...,Easy,Dessert,4.0
7,70e6bc,avocado toast,toast; avocado; salt; black pepper; cherry tom...,7,toast the bread; mash the avocado; spread it o...,Easy,Breakfast,3.9
8,b793b8,baked salmon,salmon; potatoes; olive oil; salt; black peppe...,45,slice the potatoes; place the potatoes and sal...,Medium,Lunch,0.0
9,abcf4f,mrabyan,oil; onion; garlic; black lemon; shrimp; ginge...,60,heat up oil; sautee onions with a bit of salt;...,Hard,Lunch,0.0
10,6166b7,turkey sandwich,smoked turkey; mayo; lettuce; tomato; avocado;...,10,cut the vegs; spread the mayo on the bread; ad...,Easy,Breakfast,0.0
11,33d107,tea,water; tea bag; suger,4,boil the water; add the tea bag into the cup; ...,Easy,Breakfast,4.2

In [4]:
df.loc[df['name'] == 'tea', df['category']] = 'Drink'

In [5]:
df

,id,name,ingredients,preparing time,instructions,difficulty level,category,rating,Breakfast,Breakfast,Breakfast,Breakfast,Dinner,Dinner,Lunch,Lunch,Lunch,Dessert,Dessert,Dessert
0,6aa5d9,egg sandwich,egg; tost; cheese; salt; black pepper,10,break the egg into the ban; add salt on the eg...,Easy,Breakfast,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3c2851,pasta,pasta; water; milk; cheese; tomato paste; oil;...,30,boil the pasta on the water; in another pan mi...,Medium,Dinner,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5b0334,machboose,rise; chicken; spices; potato,75,boil chicken with water and spices; boil the r...,Hard,Lunch,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5e292e,chia seed boding,chia seeds; milk; mango; yogurt; blueberry; nu...,120,add chia seed to milk and yogurt; cut the frui...,Easy,Dessert,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02621a,cesser salad,lettuce; Parmesan cheese; Caesar dressing; Gri...,20,Wash and chop the lettuce; add parmesan; Pour ...,Easy,Dinner,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1cca8b,Pancakes,flour; egg; milk; sugar; baking powder; oil; s...,20,mix all ingredients; Heat a lightly greased pa...,Medium,Dessert,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ec7ca2,fruit smoothie,banana; berries; milk; honey; ice,10,add all the ingredients to a blender; blend un...,Easy,Dessert,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,70e6bc,avocado toast,toast; avocado; salt; black pepper; cherry tom...,7,toast the bread; mash the avocado; spread it o...,Easy,Breakfast,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,b793b8,baked salmon,salmon; potatoes; olive oil; salt; black peppe...,45,slice the potatoes; place the potatoes and sal...,Medium,Lunch,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,abcf4f,mrabyan,oil; onion; garlic; black lemon; shrimp; ginge...,60,heat up oil; sautee onions with a bit of salt;...,Hard,Lunch,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,6166b7,turkey sandwich,smoked turkey; mayo; lettuce; tomato; avocado;...,10,cut the vegs; spread the mayo on the bread; ad...,Easy,Breakfast,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,33d107,tea,water; tea bag; suger,4,boil the water; add the tea bag into the cup; ...,Easy,Breakfast,4.2,Drink,Drink,Drink,Drink,Drink,Drink,Drink,Drink,Drink,Drink,Drink,Drink

In [6]:
import pandas as pd

# 1. Load the CSV file
df2 = pd.read_csv("recipes.csv")

# 2. Modify the data
# Example A: Change a specific value based on a condition
df2.drop[df2["name"] == "tea"].index.tolist()

df2

# 3. Save the changes back to the CSV
df2.to_csv("recipes.csv", index=False)

In [7]:
df2

,id,name,ingredients,preparing time,instructions,difficulty level,category,rating
0,6aa5d9,egg sandwich,egg; tost; cheese; salt; black pepper,10,break the egg into the ban; add salt on the eg...,Easy,Breakfast,2.5
1,3c2851,pasta,pasta; water; milk; cheese; tomato paste; oil;...,30,boil the pasta on the water; in another pan mi...,Medium,Dinner,4.0
2,5b0334,machboose,rise; chicken; spices; potato,75,boil chicken with water and spices; boil the r...,Hard,Lunch,4.8
3,5e292e,chia seed boding,chia seeds; milk; mango; yogurt; blueberry; nu...,120,add chia seed to milk and yogurt; cut the frui...,Easy,Dessert,2.0
4,02621a,cesser salad,lettuce; Parmesan cheese; Caesar dressing; Gri...,20,Wash and chop the lettuce; add parmesan; Pour ...,Easy,Dinner,2.2
5,1cca8b,Pancakes,flour; egg; milk; sugar; baking powder; oil; s...,20,mix all ingredients; Heat a lightly greased pa...,Medium,Dessert,3.5
6,ec7ca2,fruit smoothie,banana; berries; milk; honey; ice,10,add all the ingredients to a blender; blend un...,Easy,Dessert,4.0
7,70e6bc,avocado toast,toast; avocado; salt; black pepper; cherry tom...,7,toast the bread; mash the avocado; spread it o...,Easy,Breakfast,3.9
8,b793b8,baked salmon,salmon; potatoes; olive oil; salt; black peppe...,45,slice the potatoes; place the potatoes and sal...,Medium,Lunch,0.0
9,abcf4f,mrabyan,oil; onion; garlic; black lemon; shrimp; ginge...,60,heat up oil; sautee onions with a bit of salt;...,Hard,Lunch,0.0
10,6166b7,turkey sandwich,smoked turkey; mayo; lettuce; tomato; avocado;...,10,cut the vegs; spread the mayo on the bread; ad...,Easy,Breakfast,0.0